# Generated by Django 6.0.1 on 2026-01-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('DATA', 'Data Science & AI'), ('TOOLS', 'Tools & DevOps')], default='WEB', max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(upload_to='skills/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
