# Generated by Django 6.0.1 on 2026-01-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timelineevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='year',
            field=models.CharField(max_length=30),
        ),
    ]
