# Generated by Django 6.0.1 on 2026-01-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_timelineevent_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('FULL_STACK', 'Full Stack'), ('DATA_SCIENCE', 'Data Science'), ('SCRIPTS', 'Scripts')], default='FULL_STACK', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_link',
            field=models.URLField(blank=True),
        ),
    ]
