# Generated by Django 6.0.1 on 2026-01-17 21:15

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_category_alter_project_demo_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_ar',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fr',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category_ar',
            field=models.CharField(choices=[('FULL_STACK', 'Full Stack'), ('DATA_SCIENCE', 'Data Science'), ('SCRIPTS', 'Scripts')], default='FULL_STACK', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category_en',
            field=models.CharField(choices=[('FULL_STACK', 'Full Stack'), ('DATA_SCIENCE', 'Data Science'), ('SCRIPTS', 'Scripts')], default='FULL_STACK', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category_fr',
            field=models.CharField(choices=[('FULL_STACK', 'Full Stack'), ('DATA_SCIENCE', 'Data Science'), ('SCRIPTS', 'Scripts')], default='FULL_STACK', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_ar',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_en',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_fr',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
