# Generated by Django 6.0.1 on 2026-01-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_content_ar_post_content_en_post_content_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category_ar',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category_fr',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_fr',
        ),
    ]
